title: Semantic Versioning
descriptions: A simple set of rules and requirements that dictate how version numbers are assigned and incremented
languages:
  en: english
  fr: français
  ru: pyccкий
  uk: українська
  es: español
  it: italiano
  id: indonesia
  pt-BR: português brasileiro
  zh-TW: 繁體中文
  zh-CN: 简体中文
  ko: 한국어
  sk: slovensky
  sl: slovenščina
  ar: العربية
  ja: 日本語
  tr: Türkçe
  cs: česky
  de: deutsch
  sv: svenska
  pl: polski
  fa: فارسی
  he: עברית
  ka: ქართული
  hr: hrvatski
  hin: हिन्दी
  ca: català
  hu: magyar
  hy: Հայերեն
  kab: taqbaylit
  bg: Български
versions:
  - 2.0.0
  - 2.0.0-rc.2
  - 2.0.0-rc.1
  - 1.0.0
  - 1.0.0-beta
current_version: 2.0.0
author: Tom Preston-Werner
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
defaults:
  - scope:
      path: ''
    values:
      layout: default
